WANDB_PROJECT=embedding-malaysian-mistral-191M-32768 ~/.local/bin/deepspeed run.py \
--deepspeed ds_config_zero3.json \
--output_dir="./embedding-model-mistral-191m-contrastive" \
--model_name_or_path="mesolitica/malaysian-mistral-191M-4096" \
--train_data="/home/ubuntu/mosaic-embedding-pairs" \
--per_device_train_batch_size="2" \
--gradient_accumulation_steps 4 \
--learning_rate="2e-5" \
--num_train_epochs="2" \
--max_seq_length 8192 \
--save_steps="300" \
--save_total_limit="3" \
--do_train \
--logging_steps 1 \
--query_max_len 8192 \
--passage_max_len 8192 \
--sentence_pooling_method="cls" \
--max_grad_norm 1.0 \
--log_level="debug" \
--bf16